spring:
  application:
    name: semi
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: C##SH
    password: SH
    driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  port: 80
mybatis:
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
jwt:
  secret: D9uLKVc4FE0IEheN3pLLEb8GKhHRsG8cdOxazHnEkRm3CGAeB+xVbt8Dbob1QhRB

